# golangci-lint v2 configuration
# https://golangci-lint.run/usage/configuration/

version: "2"

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - govet         # Report suspicious constructs
    - ineffassign   # Detect unused assignments
    - staticcheck   # Static analysis checks (includes gosimple)
    - unused        # Find unused code
  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprintf
        - fmt.Printf
        - fmt.Print
        - os.Setenv
        - os.Unsetenv
